## ASSIGNMENT

### 1) GRADED

In [1]:
#import numpy library
import numpy as np

##### a) Using a for loop, iterate through the list x and print an iten if it is divisible by 2 and less than 6

e.g. x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
x = np.arange(1,11) #creating array x
print([n for n in x if n%2 == 0 and n<6])  

[2, 4]


##### b) Using a for loop, iterate through the dictionary y and print a single string of the form "company, ceo"
e.g. "CEO: Apple, Name: Tim Cook" will be the third entry for 
y = {
'Satya Nadella': 'Microsoft',
'Jeff Bezos': 'Amazon',
'Tim Cook': 'Apple'
}

In [3]:
y = {'Satya Nadella': "Microsoft", 'Jeff Bezos': 'Amazon', 'Tim Cook': 'Apple'}
for ceo, company in y.items():
    print("CEO:",company+", Name:",ceo)

CEO: Microsoft, Name: Satya Nadella
CEO: Amazon, Name: Jeff Bezos
CEO: Apple, Name: Tim Cook


### 2) GRADED

#####  (a) Complete sub_numbers so that it return difference of two numbers

In [4]:
def sub_numbers(x,y):
    return x-y
print(sub_numbers(10,2))

8


#####  (b) Write a function called mult_numbers to multiply two numbers

In [7]:
def mult_numbers(x,y):
    return x*y
print(mult_numbers(10,2))

20


### 3) GRADED

##### The following code will create arr of size 3*5.

In [8]:
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

##### (a) Determine the shape, number of dimensions and type of elements in the numpy array arr
 

In [9]:
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(3, 5)
2
int32


##### (b) Determine the sum of elements in arr

In [10]:
print(arr.sum())

105


##### (c) Determine the mean of elements in arr


In [11]:
print(arr.mean())

7.0


#####  (d) Create an array of the same shape as arr but filled with zeros

In [12]:
arr0 = np.zeros([3,5], dtype = int)
print(arr0)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#####  (e) Create an array of the same shape as arr but filled with ones

In [13]:
arr1 = np.ones([3,5], dtype = int)
print(arr1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


##### (f) Create an array of the same shape as arr but where all elements are squared values


In [14]:
arr_sq = np.power(arr,2)
print(arr_sq)

[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]]


##### (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr).

In [15]:
print(np.dot(arr,arr.transpose()))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


### 4)GRADED

##### The following piece of code creates a DataFrame

In [16]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
df.head(10)


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

##### (a) Determine the shape of the dataframe

In [17]:
print(df.shape)

(150, 5)


##### (b) Print out all the columns of the dataframe

In [18]:
print(list(df.columns))

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']


##### (c) Print the 3rd element of the dataframe

In [19]:
print(df.iloc[3])

sepal_length       4.6
sepal_width        3.1
petal_length       1.5
petal_width        0.2
species         setosa
Name: 3, dtype: object


#####  (d) Find the average of 'petal_width' where species is 'virginica'

In [20]:
print(df.loc[df["species"] == "virginica",'petal_width'].mean())

2.026


##### (e) Find the maximum of 'sepal_width' where species is 'setosa'

In [21]:
print(max(df.loc[df["species"] == "setosa",'sepal_width']))

4.4


##### (f) What is the average value of sepal_length

In [22]:
print(df['sepal_length'].mean())

5.843333333333335


##### (g) What is the maximum value of sepal_width

In [23]:
print(max(df["sepal_width"]))

4.4


##### (h) What is the minimum value of petal_width

In [24]:
print(min(df["petal_width"]))

0.1
